name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0=hd8ed1ab_2
  - anaconda-anon-usage=0.7.2=py313hfc23b7f_100
  - anaconda-auth=0.8.6=py313haa95532_0
  - anaconda-cli-base=0.5.2=py313haa95532_0
  - anaconda_powershell_prompt=1.1.0=haa95532_1
  - anaconda_prompt=1.1.0=haa95532_1
  - annotated-types=0.6.0=py313haa95532_0
  - archspec=0.2.3=pyhd3eb1b0_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=mkl
  - boltons=25.0.0=py313haa95532_0
  - bottleneck=1.4.2=py313h2cb717b_0
  - brotli-python=1.0.9=py313h5da7b33_9
  - brotlicffi=1.0.9.2=py313h5da7b33_1
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2025.8.3=py313haa95532_0
  - cffi=1.17.1=py313h827c3e9_1
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - comm=0.2.3=pyhe01879c_0
  - conda=25.7.0=py313haa95532_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313haa95532_1
  - conda-content-trust=0.2.0=py313haa95532_1
  - conda-libmamba-solver=25.4.0=pyhd3eb1b0_0
  - conda-package-handling=2.4.0=py313haa95532_0
  - conda-package-streaming=0.12.0=py313haa95532_0
  - contourpy=1.3.1=py313h214f63a_0
  - cpp-expected=1.1.0=h214f63a_0
  - cpython=3.13.7=py313hd8ed1ab_100
  - cryptography=45.0.5=py313hcaec639_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - debugpy=1.8.17=py313h927ade5_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - distro=1.9.0=py313haa95532_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h8ddb27b_0
  - fmt=9.1.0=h6d14046_1
  - fonttools=4.55.3=py313h827c3e9_0
  - freetype=2.13.3=h0620614_0
  - frozendict=2.4.2=py313haa95532_0
  - icc_rt=2022.1.0=h6049295_2
  - icu=73.1=h6c2663c_0
  - idna=3.7=py313haa95532_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2025.0.0=haa95532_1164
  - ipykernel=6.30.1=pyh3521513_0
  - ipython=9.5.0=pyh6be1c34_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=py313haa95532_0
  - jaraco.context=6.0.0=py313haa95532_0
  - jaraco.functools=4.1.0=py313haa95532_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jpeg=9f=ha349fce_0
  - jsonpatch=1.33=py313haa95532_1
  - jsonpointer=3.0.0=py313haa95532_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh5737063_0
  - keyring=25.6.0=py313haa95532_0
  - kiwisolver=1.4.8=py313h5da7b33_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libarchive=3.7.7=h9243413_0
  - libcurl=8.14.1=h2300eb9_1
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libiconv=1.16=h2bbff1b_3
  - libkrb5=1.21.3=h885b0b7_4
  - libmamba=2.0.5=hcd6fe79_1
  - libmambapy=2.0.5=py313h214f63a_1
  - libmpdec=4.0.0=h827c3e9_0
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.4=h4a159e6_2
  - libsodium=1.0.20=hc70643c_0
  - libsolv=0.7.30=hf2fb9eb_1
  - libssh2=1.11.1=h2addb87_0
  - libtiff=4.5.1=hd77b12b_0
  - libwebp-base=1.3.2=h3d04722_1
  - libxml2=2.13.8=h866ff63_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=2.2.0=py313haa95532_1
  - matplotlib=3.10.6=py313haa95532_0
  - matplotlib-base=3.10.6=py313h26e45b9_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mdurl=0.1.0=py313haa95532_0
  - menuinst=2.3.1=py313h5da7b33_0
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.4.0=py313h827c3e9_3
  - mkl_fft=1.3.11=py313h5810407_1
  - mkl_random=1.2.8=py313hedd7022_1
  - more-itertools=10.3.0=py313haa95532_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nlohmann_json=3.11.2=h6c2663c_0
  - numexpr=2.11.0=py313h7660c64_1
  - numpy=2.3.3=py313h050da96_0
  - numpy-base=2.3.3=py313h1e017a8_0
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.5.3=h725018a_0
  - packaging=25.0=py313haa95532_0
  - pandas=2.3.2=py313h42c1672_0
  - parso=0.8.5=pyhcf101f3_0
  - patsy=1.0.1=py313haa95532_0
  - pcre2=10.42=h0ff8eda_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.1.0=py313h096bfcc_0
  - pip=25.1=pyhc872135_2
  - pkce=1.0.3=py313haa95532_0
  - platformdirs=4.3.7=py313haa95532_0
  - pluggy=1.5.0=py313haa95532_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - psutil=7.1.0=py313h5ea7bf4_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h827c3e9_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pydantic=2.11.7=py313haa95532_0
  - pydantic-core=2.33.2=py313h215eeae_0
  - pydantic-settings=2.6.1=py313haa95532_0
  - pygments=2.19.1=py313haa95532_0
  - pyjwt=2.10.1=py313haa95532_0
  - pyparsing=3.2.0=py313haa95532_0
  - pyqt=6.7.1=py313h378bd72_2
  - pyqt6-sip=13.9.1=py313h02ab6af_2
  - pysocks=1.7.1=py313haa95532_0
  - python=3.13.5=h286a616_100_cp313
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-dotenv=1.1.0=py313haa95532_0
  - python-gil=3.13.7=h4df99d1_100
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=0_cp313
  - pytz=2025.2=py313haa95532_0
  - pywin32=311=py313h40c08fc_1
  - pywin32-ctypes=0.2.2=py313haa95532_0
  - pyzmq=27.1.0=py312hbb5da91_0
  - qtbase=6.7.3=hd088775_4
  - qtdeclarative=6.7.3=h885b0b7_1
  - qtsvg=6.7.3=h9d4b640_1
  - qttools=6.7.3=hcb596f7_1
  - qtwebchannel=6.7.3=h885b0b7_1
  - qtwebsockets=6.7.3=h885b0b7_1
  - readchar=4.0.5=py313haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.4=py313haa95532_0
  - rich=13.9.4=py313haa95532_0
  - ruamel.yaml=0.18.10=py313h827c3e9_0
  - ruamel.yaml.clib=0.2.12=py313h827c3e9_0
  - scipy=1.16.1=py313hbd6d557_0
  - seaborn=0.13.2=py313haa95532_3
  - semver=3.0.2=py313haa95532_1
  - setuptools=72.1.0=py313haa95532_0
  - shellingham=1.5.0=py313haa95532_0
  - simdjson=3.10.1=h214f63a_0
  - sip=6.10.0=py313h5da7b33_0
  - six=1.17.0=pyhe01879c_1
  - spdlog=1.11.0=h59b6b97_0
  - sqlite=3.50.2=hda9a48d_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - statsmodels=0.14.5=py313h2cb717b_0
  - tbb=2022.0.0=h214f63a_0
  - tbb-devel=2022.0.0=h214f63a_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py313haa95532_0
  - tornado=6.5.2=py313h5ea7bf4_1
  - tqdm=4.67.1=py313h4442805_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - truststore=0.10.1=py313haa95532_0
  - typer=0.9.0=py313haa95532_0
  - typing-extensions=4.12.2=py313haa95532_0
  - typing-inspection=0.4.0=py313haa95532_0
  - typing_extensions=4.12.2=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_0
  - xz=5.6.4=h4754444_1
  - yaml-cpp=0.8.0=hd77b12b_1
  - zeromq=4.3.5=h5bddc39_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.2.13=h8cc25b3_1
  - zstandard=0.23.0=py313h4fc1ca9_1
  - zstd=1.5.6=h8880b57_0
  - pip:
      - attrs==25.4.0
      - blinker==1.9.0
      - dash==3.3.0
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbformat==5.10.4
      - openpyxl==3.1.5
      - plotly==6.5.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - retrying==1.4.2
      - rpds-py==0.29.0
      - scikit-learn==1.7.2
      - threadpoolctl==3.6.0
      - werkzeug==3.1.3
prefix: C:\Users\mnand\miniconda3
