name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _python_abi3_support=1.0
  - anaconda-anon-usage=0.7.2
  - anaconda-auth=0.8.6
  - anaconda-cli-base=0.5.2
  - annotated-types=0.6.0
  - archspec=0.2.3
  - asttokens=3.0.0
  - blas=1.0
  - boltons=25.0.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - conda=25.7.0
  - conda-anaconda-telemetry=0.3.0
  - conda-anaconda-tos=0.2.2
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=25.4.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - contourpy=1.3.1
  - cpp-expected=1.1.0
  - cpython=3.13.7
  - cryptography=45.0.5
  - cycler=0.11.0
  - debugpy=1.8.17
  - decorator=5.2.1
  - distro=1.9.0
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - fmt=9.1.0
  - fonttools=4.55.3
  - freetype=2.13.3
  - frozendict=2.4.2
  - icu=73.1
  - idna=3.7
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jaraco.classes=3.4.0
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jpeg=9f
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - keyring=25.6.0
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lcms2=2.16
  - lerc=3.0
  - libarchive=3.7.7
  - libcurl=8.14.1
  - libdeflate=1.17
  - libffi=3.4.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libmamba=2.0.5
  - libmambapy=2.0.5
  - libmpdec=4.0.0
  - libpng=1.6.39
  - libpq=17.4
  - libsodium=1.0.20
  - libsolv=0.7.30
  - libssh2=1.11.1
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown-it-py=2.2.0
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.1.7
  - mdurl=0.1.0
  - menuinst=2.3.1
  - more-itertools=10.3.0
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.2
  - numexpr=2.11.0
  - numpy=2.3.3
  - numpy-base=2.3.3
  - openjpeg=2.5.2
  - openssl=3.5.3
  - packaging=25.0
  - pandas=2.3.2
  - parso=0.8.5
  - patsy=1.0.1
  - pcre2=10.42
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.1
  - pkce=1.0.3
  - platformdirs=4.3.7
  - pluggy=1.5.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pure_eval=0.2.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-gil=3.13.7
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pywin32=311
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readchar=4.0.5
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - rich=13.9.4
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - scipy=1.16.1
  - seaborn=0.13.2
  - semver=3.0.2
  - setuptools=72.1.0
  - shellingham=1.5.0
  - simdjson=3.10.1
  - sip=6.10.0
  - six=1.17.0
  - spdlog=1.11.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - tbb=2022.0.0
  - tbb-devel=2022.0.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typer=0.9.0
  - typing-extensions=4.12.2
  - typing-inspection=0.4.0
  - typing_extensions=4.12.2
  - tzdata=2025b
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.6.4
  - yaml-cpp=0.8.0
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - attrs==25.4.0
      - blinker==1.9.0
      - dash==3.3.0
      - et-xmlfile==2.0.0
      - fastjsonschema==2.21.2
      - flask==3.1.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.2
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.12.0
      - nbclient==0.10.2
      - nbformat==5.10.4
      - openpyxl==3.1.5
      - plotly==6.5.0
      - pyyaml==6.0.3
      - referencing==0.37.0
      - retrying==1.4.2
      - rpds-py==0.29.0
      - scikit-learn==1.7.2
      - threadpoolctl==3.6.0
      - werkzeug==3.1.3
prefix: C:\Users\mnand\miniconda3
